import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>

            </Head>
            <div className="navbar">
                <Link href="/">
                    <a className="link">Main</a>
                </Link>
                <Link href="/users">
                    <a className="link">Users</a>
                </Link>
                <style jsx>
                    {`
                      .navbar {
                        background: darkorange;
                        padding: 15px;
                      }
                      .link{
                      margin: 10px;
                      color: aliceblue;
                      font-size: 15px;
                      font-weight: bold;
                      }
                    `}

                </style>
            </div>

            <main className={styles.main}>
                Hi everyone !
            </main>

            <footer className={styles.footer}>

            </footer>
        </div>
    )
}
