import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import CustomLink from "../components/CustomLink";

export default function Home() {
    return (
        <div >
            <Head>
                <title>Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>

            </Head>
            <div className="navbar">
                <CustomLink href={"/"} text={"Main"} />
                <CustomLink href={"/users"} text={"Users"}/>

                <style jsx>
                    {`
                      .navbar {
                        background: darkorange;
                        padding: 15px;
                      }                   
                    `}

                </style>
            </div>

            <main className={styles.main}>
                Hi everyone !
            </main>

            <footer className={styles.footer}>

            </footer>
        </div>
    )
}
